// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file internal/rpc/v1/rpc.proto (package internal.rpc.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file internal/rpc/v1/rpc.proto.
 */
export const file_internal_rpc_v1_rpc: GenFile = /*@__PURE__*/
  fileDesc("ChlpbnRlcm5hbC9ycGMvdjEvcnBjLnByb3RvEg9pbnRlcm5hbC5ycGMudjEiIAoIUG9zaXRpb24SCQoBeBgBIAEoAxIJCgF5GAIgASgDIhkKCE5vZGVEYXRhEg0KBWxhYmVsGAEgASgJInYKBE5vZGUSCgoCaWQYASABKAkSKwoIcG9zaXRpb24YAiABKAsyGS5pbnRlcm5hbC5ycGMudjEuUG9zaXRpb24SJwoEZGF0YRgDIAEoCzIZLmludGVybmFsLnJwYy52MS5Ob2RlRGF0YRIMCgR0eXBlGAQgASgJIkAKBEVkZ2USCgoCaWQYASABKAkSDgoGc291cmNlGAIgASgJEg4KBnRhcmdldBgDIAEoCRIMCgR0eXBlGAQgASgJIvQBChJSYW5kb21HcmFwaFJlcXVlc3QSDQoFc2VlZDEYASABKAQSDQoFc2VlZDIYAiABKAQSEQoJbnVtX25vZGVzGAMgASgDEhkKEWluaXRpYWxfY29ubmVjdGVkGAQgASgDEhwKFHJld2lyaW5nX3Byb2JhYmlsaXR5GAUgASgBEhkKEWxheW91dF9pdGVyYXRpb25zGAYgASgDEhMKC2xheW91dF9hcmVhGAcgASgBEhMKC3dhbGtfbGVuZ3RoGAggASgDEhEKCW51bV93YWxrcxgJIAEoAxINCgVzZWVkMxgKIAEoBBINCgVzZWVkNBgLIAEoBCJhChNSYW5kb21HcmFwaFJlc3BvbnNlEiQKBW5vZGVzGAEgAygLMhUuaW50ZXJuYWwucnBjLnYxLk5vZGUSJAoFZWRnZXMYAiADKAsyFS5pbnRlcm5hbC5ycGMudjEuRWRnZTJoCgxHcmFwaFNlcnZpY2USWAoLUmFuZG9tR3JhcGgSIy5pbnRlcm5hbC5ycGMudjEuUmFuZG9tR3JhcGhSZXF1ZXN0GiQuaW50ZXJuYWwucnBjLnYxLlJhbmRvbUdyYXBoUmVzcG9uc2VCrAEKE2NvbS5pbnRlcm5hbC5ycGMudjFCCFJwY1Byb3RvUAFaLWdpdGh1Yi5jb20vYWR2ZHYvdHJ1c3RkL2ludGVybmFsL3JwYy92MTtycGN2MaICA0lSWKoCD0ludGVybmFsLlJwYy5WMcoCD0ludGVybmFsXFJwY1xWMeICG0ludGVybmFsXFJwY1xWMVxHUEJNZXRhZGF0YeoCEUludGVybmFsOjpScGM6OlYxYghlZGl0aW9uc3DoBw");

/**
 * @generated from message internal.rpc.v1.Position
 */
export type Position = Message<"internal.rpc.v1.Position"> & {
  /**
   * @generated from field: int64 x = 1;
   */
  x: bigint;

  /**
   * @generated from field: int64 y = 2;
   */
  y: bigint;
};

/**
 * Describes the message internal.rpc.v1.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export const PositionSchema: GenMessage<Position> = /*@__PURE__*/
  messageDesc(file_internal_rpc_v1_rpc, 0);

/**
 * @generated from message internal.rpc.v1.NodeData
 */
export type NodeData = Message<"internal.rpc.v1.NodeData"> & {
  /**
   * @generated from field: string label = 1;
   */
  label: string;
};

/**
 * Describes the message internal.rpc.v1.NodeData.
 * Use `create(NodeDataSchema)` to create a new message.
 */
export const NodeDataSchema: GenMessage<NodeData> = /*@__PURE__*/
  messageDesc(file_internal_rpc_v1_rpc, 1);

/**
 * @generated from message internal.rpc.v1.Node
 */
export type Node = Message<"internal.rpc.v1.Node"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: internal.rpc.v1.Position position = 2;
   */
  position?: Position;

  /**
   * @generated from field: internal.rpc.v1.NodeData data = 3;
   */
  data?: NodeData;

  /**
   * @generated from field: string type = 4;
   */
  type: string;
};

/**
 * Describes the message internal.rpc.v1.Node.
 * Use `create(NodeSchema)` to create a new message.
 */
export const NodeSchema: GenMessage<Node> = /*@__PURE__*/
  messageDesc(file_internal_rpc_v1_rpc, 2);

/**
 * @generated from message internal.rpc.v1.Edge
 */
export type Edge = Message<"internal.rpc.v1.Edge"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string source = 2;
   */
  source: string;

  /**
   * @generated from field: string target = 3;
   */
  target: string;

  /**
   * @generated from field: string type = 4;
   */
  type: string;
};

/**
 * Describes the message internal.rpc.v1.Edge.
 * Use `create(EdgeSchema)` to create a new message.
 */
export const EdgeSchema: GenMessage<Edge> = /*@__PURE__*/
  messageDesc(file_internal_rpc_v1_rpc, 3);

/**
 * @generated from message internal.rpc.v1.RandomGraphRequest
 */
export type RandomGraphRequest = Message<"internal.rpc.v1.RandomGraphRequest"> & {
  /**
   * @generated from field: uint64 seed1 = 1;
   */
  seed1: bigint;

  /**
   * @generated from field: uint64 seed2 = 2;
   */
  seed2: bigint;

  /**
   * @generated from field: int64 num_nodes = 3;
   */
  numNodes: bigint;

  /**
   * @generated from field: int64 initial_connected = 4;
   */
  initialConnected: bigint;

  /**
   * @generated from field: double rewiring_probability = 5;
   */
  rewiringProbability: number;

  /**
   * @generated from field: int64 layout_iterations = 6;
   */
  layoutIterations: bigint;

  /**
   * @generated from field: double layout_area = 7;
   */
  layoutArea: number;

  /**
   * @generated from field: int64 walk_length = 8;
   */
  walkLength: bigint;

  /**
   * @generated from field: int64 num_walks = 9;
   */
  numWalks: bigint;

  /**
   * @generated from field: uint64 seed3 = 10;
   */
  seed3: bigint;

  /**
   * @generated from field: uint64 seed4 = 11;
   */
  seed4: bigint;
};

/**
 * Describes the message internal.rpc.v1.RandomGraphRequest.
 * Use `create(RandomGraphRequestSchema)` to create a new message.
 */
export const RandomGraphRequestSchema: GenMessage<RandomGraphRequest> = /*@__PURE__*/
  messageDesc(file_internal_rpc_v1_rpc, 4);

/**
 * @generated from message internal.rpc.v1.RandomGraphResponse
 */
export type RandomGraphResponse = Message<"internal.rpc.v1.RandomGraphResponse"> & {
  /**
   * @generated from field: repeated internal.rpc.v1.Node nodes = 1;
   */
  nodes: Node[];

  /**
   * @generated from field: repeated internal.rpc.v1.Edge edges = 2;
   */
  edges: Edge[];
};

/**
 * Describes the message internal.rpc.v1.RandomGraphResponse.
 * Use `create(RandomGraphResponseSchema)` to create a new message.
 */
export const RandomGraphResponseSchema: GenMessage<RandomGraphResponse> = /*@__PURE__*/
  messageDesc(file_internal_rpc_v1_rpc, 5);

/**
 * @generated from service internal.rpc.v1.GraphService
 */
export const GraphService: GenService<{
  /**
   * @generated from rpc internal.rpc.v1.GraphService.RandomGraph
   */
  randomGraph: {
    methodKind: "unary";
    input: typeof RandomGraphRequestSchema;
    output: typeof RandomGraphResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_internal_rpc_v1_rpc, 0);

